name: Release Please

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: stremio-showbox-scraper
          
      # Optional: Deploy or publish after release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '18'
          
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
        
      # Add any deployment steps here if needed
      # - name: Deploy
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: npm run deploy